In [1]:
import pandas as pd

In [4]:
pd.read_csv('../data/clear/poblacion_caba.csv',sep=";")

    comuna     2016     2017     2018     2019     2020     2021     2022
0        1  252.053  253.271  254.408  255.457  256.405  257.235  257.934
1        2  149.848  149.720  149.607  149.510  149.430  149.371  149.337
2        3  192.573  192.763  192.945  193.115  193.276  193.425  193.560
3        4  238.303  238.809  239.279  239.712  240.100  240.437  240.716
4        5  186.740  186.956  187.159  187.348  187.518  187.670  187.800
5        6  184.611  184.846  185.067  185.271  185.456  185.620  185.760
6        7  240.116  240.607  241.065  241.484  241.861  242.188  242.460
7        8  225.737  226.649  227.495  228.266  228.953  229.541  230.018
8        9  170.353  170.605  170.842  171.062  171.264  171.444  171.600
9       10  170.163  170.282  170.394  170.497  170.592  170.677  170.750
10      11  189.956  189.986  190.016  190.046  190.076  190.105  190.135
11      12  213.576  213.914  214.229  214.518  214.777  215.002  215.189
12      13  235.819  235.967  236.107  236.238  236.358  236.468  236.566
13      14  226.884  226.944  227.003  227.060  227.115  227.168  227.219
14      15  182.390  182.409  182.427  182.445  182.465  182.485  182.506